### ISSUE TITLE
Remaping of species property name in sandbox

### ISSUE THREAD

**Issue by Kris2k** [qsorix/battle-of-nilmacs#2]
In creating species in file e.g
players/sample.lua

developer should assign name to species by using 
species.name = "sample"

but to refer to to others player creatures(species) you should do
local sees = Action.Look(3)
sees[1].species 
not sees[1].name 
or sees[1].species.name

This is due to 
game.lua:275 which does 'remaping' property. 

Fix by eiter:
 - using sees[1].species and player should "name" the creature by assigning to species.species =' some fancy name'
 - using sees[1].name 

everywhere 
I would like the second resolution species.species sounds funny

**Comment by qsorix** [comment]
Implemented
